const primaryColors = require("@left4code/tw-starter/dist/js/colors");

module.exports = {
    mode: "jit",
    purge: [
        "./src/**/*.{php,html,js,jsx,ts,tsx,vue}",
        "./resources/**/*.{php,html,js,jsx,ts,tsx,vue}",
        "./node_modules/@left4code/tw-starter/**/*.js",
        "./*.{php,html,js,jsx,ts,tsx,vue}",
        //".//.html",
    ],
    darkMode: "class",
    theme: {
        borderColor: (theme) => ({
            ...theme("colors"),
            DEFAULT: primaryColors.gray["300"],
        }),
        colors: {
            ...primaryColors,
            primary: {
                ...primaryColors.primary,
                1: "#142E71",
            },
            dark: {
                ...primaryColors.dark,
                8: "#242b3c",
            },
            white: "white",
            black: "black",
            current: "current",
            transparent: "transparent",
            theme: {
                1: "#071A50",
                2: "#2D427B",
                3: "#A2AFD5",
                4: "#C6D4FD",
                5: "#D32929",
                6: "#365A74",
                7: "#D2DFEA",
                8: "#7F9EB8",
                9: "#96A5D0",
                10: "#13B176",
                11: "#11296d",
                12: "#1f377d",
                13: "#9BADE4",
                14: "#1c3271",
                15: "#F1F5F8",
                16: "#102867",
                17: "#142E71",
                18: "#172F71",
                19: "#B2BEDE",
                20: "#102765",
                21: "#3160D8",
                22: "#F78B00",
                23: "#FBC500",
                24: "#CE3131",
                25: "#E2EBF2",
                26: "#203f90",
                27: "#8DA9BE",
                28: "#607F96",
                29: "#B8F1E1",
                30: "#FFE7D9",
                31: "#DBDFF9",
                32: "#2B4286",
                33: "#8C9DCA",
                34: "#0E2561",
                35: "#E63B1F",
            },
        },
        
        extend: {
            colors: {
                primary: "var(--primary)",
                secondary: "var(--secondary)",
                main: "var(--main)",
                background: "var(--background)",
                header: "var(--header)",
                accent: "var(--accent)",
                'primary-0': 'var(--primary-0)',
                'primary-1': 'var(--primary-1)',
                'primary-2': 'var(--primary-2)',
                'primary-3': 'var(--primary-3)',
                'primary-4': 'var(--primary-4)',
                'primary-5': 'var(--primary-5)',
                'primary-6': 'var(--primary-6)',
                'primary-7': 'var(--primary-7)',
                'primary-8': 'var(--primary-8)',
                'primary-9': 'var(--primary-9)',
                'secondary-0': 'var(--secondary-0)',
                'secondary-1': 'var(--secondary-1)',
                'secondary-2': 'var(--secondary-2)',
                'secondary-3': 'var(--secondary-3)',
                'secondary-4': 'var(--secondary-4)',
                'secondary-5': 'var(--secondary-5)',
                'secondary-6': 'var(--secondary-6)',
                'secondary-7': 'var(--secondary-7)',
                'secondary-8': 'var(--secondary-8)',
                'secondary-9': 'var(--secondary-9)',
                'secondary-10': 'var(--secondary-10)',
            },
            fontFamily: {
                roboto: ["Roboto"],
            },
            container: {
                center: true,
            },
            maxWidth: {
                "1/4": "25%",
                "1/2": "50%",
                "3/4": "75%",
            },
            strokeWidth: {
                0.5: 0.5,
                1.5: 1.5,
                2.5: 2.5,
            },
        },
    },
    variants: {
        extend: {
            boxShadow: ["dark"],
        },
    },
};
